### ISSUE TITLE
Signup count & highlight recent signups

### ISSUE THREAD

**Issue by anom** [arfie/eltp-draft-packet#5]
1. Signup count
2. Highlight recent sign ups

Thoughts?

**Comment by zeeres** [comment]
I'd +1 a signup count. It could also be used to display the number of people who match the currently applied filter.

**Comment by arfie** [comment]
Signup count is a thing others have requested as well. My current plan is to just have line numbers like in a googledoc.

New players is also a good one. Not a priority but I have some ideas for how I could do that.

**Comment by anom** [comment]
Regarding signup count, I think it'll be good to have it in the title.

`ELTP Draft Packer - 103 players`
